### ISSUE TITLE
[ HELP] Usage in Typescript

### ISSUE THREAD

**Issue by sojeda** [chamindu/optimus-js#3]
I trying use optimus-js in a TS project. I get the following error:

`TypeError: optimus_js_1.default is not a constructor
    at bootstrap (D:\Code\services-billing-v2\src\main.ts:17:19)
    at Object.<anonymous> (D:\Code\services-billing-v2\src\main.ts:50:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module.m._compile (D:\Code\services-billing-v2\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.require.extensions.<computed> [as .ts] (D:\Code\services-billing-v2\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
`

My code is:

`
import Optimus from "optimus-js";
const optimus = new Optimus(1580030173, 59260789, 1163945558);
`

Any ideas? Thanks!

**Comment by sojeda** [comment]
I decided change for https://github.com/frolovdev/easymoney

**Comment by sojeda** [comment]
Solution: Change for https://www.npmjs.com/package/inthash
